# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_talk',
                'doc_host': 'https://arunslb123.github.io',
                'git_url': 'https://github.com/arunslb123/nbdev_talk',
                'lib_path': 'nbdev_talk'},
  'syms': {'nbdev_talk.core': {'nbdev_talk.core.foo': ('core.html#foo', 'nbdev_talk/core.py')}}}
